name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)
trigger:
- feature/private-agent
- main

variables:
  pool: default_windows
  system.debug: 'true'

stages:
- stage: DEMO
  displayName: Demo
  variables:
    applicationsList: app1,app2,app3
  jobs:
  - template: child.yml
    parameters:
      applicationsToExclude: app2
      folders: ['app1','app2','app3']
